[server]
headless = true
address = "0.0.0.0"
port = 8501
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#3157F5"
backgroundColor = "#FBFCFF"
secondaryBackgroundColor = "#F2F5FB"
textColor = "#15233C"
font = "sans serif"
